media: public/media
content:
  - name: leaders
    label: Leaders
    type: collection
    path: src/_data/leaders
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: role
        label: Leadership Role
        type: string
        required: true
      - name: description
        label: Personal Description
        type: text
        required: true
      - name: linkedin
        label: Link to linkedin profile (optional)
        type: string
      - name: github
        label: Link to github profile (optional)
        type: string
      - name: image
        label: Photo of you
        type: image
        required: true
  - name: outreach
    label: Outreach
    type: collection
    path: src/_data/outreach
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle 
        type: string
        required: false
      - name: description
        label: Event Description
        type: text
        required: true
      - name: image
        label: Event photo
        type: image
        required: true
  - name: sponsors
    label: Sponsors
    type: collection
    path: src/_data/sponsors
    fields:
      - name: name
        label: Sponsor Name
        type: string
        required: true
      - name: logo
        label: Sponsor Logo
        type: image
        required: true
      - name: description
        label: Sponsor Description
        type: text
        required: true
      - name: tier
        label: Sponsorship Tier
        type: select
        options:
          Platinum:
            label: Platinum
            type: string
          Gold:
            label: Gold
            type: string
          Silver:
            label: Silver
            type: string
          Bronze:
            label: Bronze
            type: string
        required: true
      - name: website
        label: Sponsor Website
        type: string
        required: false
  - name: blog
    label: Blog Posts
    type: collection
    path: src/_data/blog
    fields:
      - name: title
        label: Post Title
        type: string
        required: true
      - name: date
        label: Publication Date
        type: date
        required: true
      - name: author
        label: Author Name
        type: string
        required: true
      - name: category
        label: Category
        type: select
        options:
          Competition Updates:
            label: Competition Updates
            type: string
          Build Progress:
            label: Build Progress
            type: string
          Team News:
            label: Team News
            type: string
          Technical Articles:
            label: Technical Articles
            type: string
          Community Events:
            label: Community Events
            type: string
        required: true
      - name: description
        label: Short Description
        type: text
        required: true
      - name: content
        label: Post Content
        type: text
        required: true
      - name: image
        label: Featured Image
        type: image
        required: true
      - name: tags
        label: Tags
        type: string
        required: false